import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import 'reflect-metadata'

const expo2 = localFont({
	src: './fonts/Exo2-VariableFont_wght.ttf',
	variable: '--font-expo-2',
})
const expo2Italic = localFont({
	src: './fonts/Exo2-Italic-VariableFont_wght.ttf',
	variable: '--font-expo-2-italic',
})

export const metadata: Metadata = {
	title: 'Photo Land',
	description: 'Generated by Ahmed Abdelfattah',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='en'
			className={`${expo2.variable} ${expo2Italic.variable} antialiased`}
		>
			<body className='font-expo'>{children}</body>
		</html>
	)
}
